name: Ping Pong

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ping_pong:

    runs-on: ubuntu-latest

    steps:
    - name: Pong
      run: echo "Pong!"

    - name: Ping
      run: echo "Ping!"
